apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.99.101
      user: vagrant
      port: 22
      keyPath: ~/.vagrant.d/insecure_private_key
    role: controller
    privateAddress: 192.168.99.101
  - ssh:
      address: 192.168.99.102
      user: vagrant
      port: 22
      keyPath: ~/.vagrant.d/insecure_private_key
    role: worker
    privateAddress: 192.168.99.102
  - ssh:
      address: 192.168.99.103
      user: vagrant
      port: 22
      keyPath: ~/.vagrant.d/insecure_private_key
    role: worker
    privateAddress: 192.168.99.103
  k0s:
    version: v1.28.4+k0s.0
    dynamicConfig: false
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          k0sApiPort: 9443
          port: 6443
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        konnectivity:
          adminPort: 8133
          agentPort: 8132
        network:
          kubeProxy:
            disabled: false
            mode: iptables
          kuberouter:
            autoMTU: true
            mtu: 0
            peerRouterASNs: ""
            peerRouterIPs: ""
          podCIDR: 10.244.0.0/16
          provider: kuberouter
          serviceCIDR: 10.96.0.0/12
        podSecurityPolicy:
          defaultPolicy: 00-k0s-privileged
        storage:
          type: etcd
        telemetry:
          enabled: true
